[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# se um dia você usar rotas reais:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
